version: '3'
services:
  php:
    container_name: laravel-php
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
      - ./build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html:cached
    expose:
      - 9000
    networks:
      - php-network
  nginx:
    container_name: laravel-nginx
    image: nginx
    volumes:
      - .:/var/www/html:cached
      - ./build/nginx:/etc/nginx/conf.d
    working_dir: /var/www/html/public
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - php-network
  laravel:
    container_name: laravel-app
    image: php:8.1-fpm
    command: bash -c "
      if ![-f '.env']; then cp .env.example .env; fi &&
      chmod -R 777 storage &&
      if ! [ -d 'vendor' ]; then composer update --no-ansi --no-interaction --no-progress --optimize-autoloader --prefer-dist; fi &&
      if ! grep -Fq "APP_KEY=base64:" .env ; then php artisan key:generate; fi &&
      php artisan key:generate"
    depends_on:
      - php
    volumes:
      - .:/var/www/html:cached
networks:
  php-network:
    driver: bridge
