version: '3'
services:
  php:
    container_name: ${APP_NAME}-php
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
      - ./build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    expose:
      - 9000
    networks:
      - php-network
  composer:
    container_name: ${APP_NAME}-composer
    image: composer
    volumes:
      - .:/var/www/html:cached
    command: sh -c "
      composer install --ignore-platform-reqs &&
      php artisan key:generate"
    working_dir: /var/www/html
    depends_on:
      - php
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx
    volumes:
      - .:/var/www/html:cached
      - ./build/nginx:/etc/nginx/conf.d
    working_dir: /var/www/html/public
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - php-network
  node:
    command: sh -c "yarn && yarn run watch"
    container_name: ${APP_NAME}-node
    image: node
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html

  postgres:
    image: postgres
    container_name: ${APP_NAME}-postgres
    volumes:
      - "./build/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - php-network
    depends_on:
      - php
      - nginx
networks:
  php-network:
    driver: bridge
